before_script:
   - apt-get update -qy
   - apt-get install -y python-dev python-pip
#   - pip install -r requirements.txt # CI can't handle fbprophet since it requires 4GB memory for installation

stages:
   - build
   - test

build:
   stage: build
   script:
   - echo "Building..."
   
test:
   stage: test
   script:
      - echo "Testing..."

